"""add company_name role color to deadlines

Revision ID: bf7052073f53
Revises: 17a1a21186b6
Create Date: 2026-03-17 02:07:10.938053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7052073f53'
down_revision = '17a1a21186b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deadlines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deadlines', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('role')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
